### ISSUE TITLE
materials/plastic3.py has bad call to symmetric_dyad()

### ISSUE THREAD

**Issue by sswan** [matmodlab/matmodlab2#12]
While running HardeningJ2Plasticity.ipynb it failed when trying to run plastic3.py because of a call to symmetric_dyad() in core/tensor.py. I believe that the problem is that symmetric_dyad() expects two length-3 arrays but it's used in plastic3.py as a way to construct a 4th-order tensor from two 2nd order tensors.

As such, HardeningJ2Plasticity.ipynb cannot be run.

**Comment by sswan** [comment]
Similar issue in plastic2.py while running NonhardeningJ2Plasticity.ipynb

**Comment by tjfulle** [comment]
Arghhh!  There is a dyad function in `core/tensor.py` that takes second order tensors as input.  I'll fix this later today.

**Comment by sswan** [comment]
Don't worry about it, Tim. I'll take care of it.

I've been going through each ipynb and making sure that it runs as expected and fixing any errors. This was an error that I opened the tracker so it could be treated later. I'll commit a fix with the other fixes.

**Comment by tjfulle** [comment]
@sswan , okay.  `core/tensor.py` was generated by Mathematica and not intended to be read/modified (though, I don't have the original notebook anymore).  So, it's not "pretty".  There should probably be a single `symmetric_dyad` function that branches to different implementations depending on input.  At least, that's what I thought it currently did.

**Comment by sswan** [comment]
There are separate symmetric_dyad() and dyad() functions. The former is for length-3 vectors to create a 2nd order symmetric tensor. The latter is for length-6 vectors (2nd order tensors) to create a 4th order tensor. The only change required was changing "symmetric_dyad()" to "dyad()" in plastic2.py and plastic3.py. I'll close the tracker when my changes are committed.

**Comment by tjfulle** [comment]
It looks like `core.tensor.dyad` is the right function.  I thought there was just a single Fuad function, I guess there are 2.

**Comment by sswan** [comment]
commit 4dd4a882a9992491e0fd6f0432de6c3a7ad17871 fixes the issue.
