### ISSUE TITLE
Issue with "mml test"

### ISSUE THREAD

**Issue by udayanghosh** [matmodlab/matmodlab2#15]
I am getting this error when I tried to follow the installation instruction and could not run it. Can you please take a look into it?

udayan@MEB-3560-02:~/Downloads/matmodlab-3.0.6/matmodlab$ mml test
Traceback (most recent call last):
  File "/home/udayan/anaconda3/bin/mml", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/udayan/Downloads/matmodlab-3.0.6/matmodlab/bin/mml", line 7, in <module>
    from matmodlab.mmd.startup import main
  File "/home/udayan/Downloads/matmodlab-3.0.6/matmodlab/__init__.py", line 8, in <module>
    from StringIO import StringIO
ImportError: No module named 'StringIO'

Thanks

**Comment by sswan** [comment]
This looks like a python2/python3 issue. Make sure you're running it with
the correct one (whatever that may be for the version you have checked out).

Scot

**Comment by tjfulle** [comment]
Thanks for opening this issue @udayanghosh!  The `StringIO` module has been removed from Python3, so you will need to use Python2 for the version of Matmodlab you have installed.  It appears that you are using the version installed via pip.  That is fine (so long as you are using the right version of Python), however, I *strongly* recommend cloning and using the most up to date version of Matmodlab from this repository.  The pypi version (installed by pip) will never be as up to date as the repository version.

Note, it is not stated explicitly in the documentation, but the latest version of matmodlab in the repository requires Python3 (which you are already using).  Also, the `mml` command has been removed.  Instead, just use straight python (or a Jupyter notebook).  i.e., `python myscript.py`.  To run the tests, just run `py.test` from the `matmodlab2/tests` directory.

Like many open source projects, the documentation can *always* use more work and updating.

**Comment by tjfulle** [comment]
@udayanghosh , also, to get started using `matmodlab`, I recommend going through the tutorial notebooks.  You can view them online at: [Notebooks](https://github.com/matmodlab/matmodlab2/blob/master/notebooks/Introduction.ipynb), or run them directly by navigating to the `matmodlab2/notebooks` directory and launching Jupyter notebook.

**Comment by tjfulle** [comment]
@udayanghosh, on further investigation, it appears you are using *matmodlab*, that version has been superseded by *matmodlab2* (the code in this repository).

I just updated the `README` with some installation instructions.

**Comment by udayanghosh** [comment]
Thanks a lot both of you @tjfulle  and @sswan .......Now I've been able to use it.
